title: N74NK
description: "Developer malas yang mimpinya pengen sukses."
permalink: ':title/'
baseurl: ""
url: "https://n74nk.github.io"
site-twitter:

author: Njank Yuti
author-img: david-freeman.jpg
about-author: I am a newbie developer focusing on all-end development. Always hungry to keep learning.

social-youtube: NjankSoekamti
social-facebook: njnk.xnxx
social-github: N74NK
social-instagram: n74nk420
social-email: dindacgr2@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 7
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
