# Site settings
title: N74NK
email: dindacgr2@gmail.com
description: "Developer malas yang mimpinya pengen sukses." # > this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://n74nk.github.io" # the base hostname & protocol for your site

twitter_username:
github_username: N74NK

# Build settings
markdown: kramdown
