# google_analytics: UA-NNNNNNNN-N
# listen_for_clients_preferred_style: true # true or false (default)

header_pages:
  - index.md
  - about.md
  - profile.md

footer: 'Developed by <a href="https://github.com/N74NK/">Njank</a>'

style: dark

plugins:
  - jekyll-seo-tag
